version: 1.0.{build}
configuration: Release
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
  
build_script:
- ps: .\build.ps1 -experimental

test: off

deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: liSTqN52OJQy9fZJk6gubSgYBAy4EXcEPCDSCLJ/3T9cZufzpTwvBlGPLX+iP2n9

artifacts:
- path: nupkg\*.nupkg
  name: nuget-packages
