version: 1.0.{build}
configuration: Release
image: Visual Studio 2017 RC
pull_requests:  
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
environment:
  nuget_user: oguzhansoykan@outlook.com
  nuget_password:
    secure: w73Xs1Is7iK/DtAOf0XTHg==
    
before_build:
 - cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%
 - cmd: nuget install nuget.commandline -source https://dotnet.myget.org/F/nuget-build -prerelease -excludeversion
 - cmd: set PATH=%appveyor_build_folder%\NuGet.CommandLine\tools;%PATH%
 - cmd: nuget restore Stove.sln 
  
build:
  project: Stove.sln 
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
 
test:
  assemblies:
  - test\Stove.EntityFramework.Tests\bin\Debug\net461\win7-x64\Stove.EntityFramework.Tests.dll
  - test\Stove.Mapster.Tests\bin\Debug\net461\win7-x64\Stove.Mapster.Tests.dll
  - test\Stove.RabbitMQ.Tests\bin\Debug\net461\win7-x64\Stove.RabbitMQ.Tests.dll
  - test\Stove.Tests\bin\Debug\net461\win7-x64\Stove.Tests.dll
  - test\Stove.Tests.SampleApplication\bin\Debug\net461\win7-x64\Stove.Tests.SampleApplication.dll
  
deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: liSTqN52OJQy9fZJk6gubSgYBAy4EXcEPCDSCLJ/3T9cZufzpTwvBlGPLX+iP2n9
artifacts:
- path: '**\.nupkg/'
