version: 1.0.{build}
pull_requests:  
  do_not_increment_build_number: true
before_build:
- cmd: dotnet.exe restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_user: oguzhansoykan@outlook.com
  nuget_password:
    secure: w73Xs1Is7iK/DtAOf0XTHg==
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: dotnet pack "src\Stove" -c "Release" -o "nupkg/"
- cmd: dotnet pack "src\Stove.EntityFramework" -c "Release" -o "nupkg/"
- cmd: dotnet pack "src\Stove.Hangfire" -c "Release" -o "nupkg/"
- cmd: dotnet pack "src\Stove.NLog" -c "Release" -o "nupkg/"
- cmd: dotnet pack "src\Stove.Mapster" -c "Release" -o "nupkg/"
- cmd: dotnet pack "src\Stove.Redis" -c "Release" -o "nupkg/"
- cmd: dotnet pack "src\Stove.Dapper" -c "Release" -o "nupkg/"
- cmd: dotnet pack "src\Stove.RabbitMQ" -c "Release" -o "nupkg/"
 
test:
  assemblies:
  - test\Stove.EntityFramework.Tests\bin\Debug\net461\win7-x64\Stove.EntityFramework.Tests.dll
  - test\Stove.Mapster.Tests\bin\Debug\net461\win7-x64\Stove.Mapster.Tests.dll
  - test\Stove.RabbitMQ.Tests\bin\Debug\net461\win7-x64\Stove.RabbitMQ.Tests.dll
  - test\Stove.Tests\bin\Debug\net461\win7-x64\Stove.Tests.dll
  - test\Stove.Tests.SampleApplication\bin\Debug\net461\win7-x64\Stove.Tests.SampleApplication.dll
  
deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: liSTqN52OJQy9fZJk6gubSgYBAy4EXcEPCDSCLJ/3T9cZufzpTwvBlGPLX+iP2n9
artifacts:
- path: '**\.nupkg/'
