version: 1.0.{build}
configuration: Release

before_build:
- cmd: nuget.exe restore

build:
  verbosity: minimal

test:
  assemblies:
  - test\Stove.EntityFramework.Tests
  - test\Stove.Tests
